source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'pg'
gem 'jquery-rails'
gem 'haml'
gem 'newrelic_rpm'


group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'

end


group :development, :test do
	gem 'pry-rails'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'

  gem 'quiet_assets'
  gem 'binding_of_caller'
  gem 'meta_request'

  gem 'annotate'

  gem 'rspec-rails'
  gem 'faker'
  gem 'factory_girl_rails'

  gem 'capybara'
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'rb-fsevent'
  gem 'webrat'
  gem 'shoulda-matchers'
end


group :development do  
	gem 'better_errors'
end
