Species.delete_all
Aquarium.delete_all
Fish.delete_all
User.delete_all

s1 = Species.create(price: 1, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-872548.gif', name: 'Guppy', appetite: 150, cleanliness_level: 100)
s2 = Species.create(price: 1, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-667949.gif', name: 'Reedfish', appetite: 100, cleanliness_level: 90)  #
s4 = Species.create(price: 4, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-038894.gif', name: 'Longnose gar', appetite: 80, cleanliness_level: 80)
s5 = Species.create(price: 6, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-048465.gif', name: 'Ray', appetite: 40, cleanliness_level: 70)
s6 = Species.create(price: 6, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-873579.gif', name: 'Clam', appetite: 1, cleanliness_level: 150)
s7 = Species.create(price: 7, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-212867.gif', name: 'Red Lion Fish', appetite: 35, cleanliness_level: 80)
s8 = Species.create(price: 9, image: 'http://animationsa2z.com/attachments/Image/turtle/turtle10.gif', name: 'Turtle', appetite: 55, cleanliness_level: 85) #
s9 = Species.create(price: 13, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-357740.gif', name: 'Carpenters Flasher Wrasse', appetite: 60, cleanliness_level: 70)
s10 = Species.create(price: 14, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-803819.gif', name: 'Blue Headed Wrasse', appetite: 45, cleanliness_level: 40) #
s11 = Species.create(price: 16, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-522808.gif', name: 'Harlequin Tusk Fish', appetite: 45, cleanliness_level: 45) #
s12 = Species.create(price: 18, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-591661.gif', name: 'Emperor Angel Fish', appetite: 40, cleanliness_level: 30) #
s13 = Species.create(price: 20, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-335526.gif', name: 'Flame Angel', appetite: 35, cleanliness_level: 25) #
s14 = Species.create(price: 22, image: 'http://www.picgifs.com/animal-graphics/animal-graphics/squid/animal-graphics-squid-833230.gif', name: 'Squid', appetite: 35, cleanliness_level: 20) #
s15 = Species.create(price: 22, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-486837.gif', name: 'Yellow Fin Fairy Wrasse', appetite: 25, cleanliness_level: 25) #
s16 = Species.create(price: 25, image: 'http://www.picgifs.com/graphics/f/fish/graphics-fish-120285.gif', name: 'Shark', appetite: 20, cleanliness_level: 20) #

a1 = Aquarium.create(fish_capacity: 3, price: 30)
a2 = Aquarium.create(fish_capacity: 5, price: 55)
a3 = Aquarium.create(fish_capacity: 8, price: 95)
a4 = Aquarium.create(fish_capacity: 15, price: 250)
a11 = Aquarium.create(fish_capacity: 3, price: 30)
a12 = Aquarium.create(fish_capacity: 5, price: 55)
a13 = Aquarium.create(fish_capacity: 8, price: 95)
a14 = Aquarium.create(fish_capacity: 15, price: 250)
a21 = Aquarium.create(fish_capacity: 3, price: 30)
a22 = Aquarium.create(fish_capacity: 5, price: 55)
a23 = Aquarium.create(fish_capacity: 8, price: 95)
a24 = Aquarium.create(fish_capacity: 15, price: 250)
a31 = Aquarium.create(fish_capacity: 3, price: 30)
a32 = Aquarium.create(fish_capacity: 5, price: 55)
a33 = Aquarium.create(fish_capacity: 8, price: 95)
a34 = Aquarium.create(fish_capacity: 15, price: 250)
a41 = Aquarium.create(fish_capacity: 3, price: 30)
a42 = Aquarium.create(fish_capacity: 5, price: 55)
a43 = Aquarium.create(fish_capacity: 8, price: 95)
a44 = Aquarium.create(fish_capacity: 15, price: 250)
a51 = Aquarium.create(fish_capacity: 3, price: 30)
a52 = Aquarium.create(fish_capacity: 5, price: 55)
a53 = Aquarium.create(fish_capacity: 8, price: 95)
a54 = Aquarium.create(fish_capacity: 15, price: 250)
a61 = Aquarium.create(fish_capacity: 3, price: 30)
a62 = Aquarium.create(fish_capacity: 5, price: 55)
a63 = Aquarium.create(fish_capacity: 8, price: 95)
a64 = Aquarium.create(fish_capacity: 15, price: 250)
a71 = Aquarium.create(fish_capacity: 3, price: 30)
a72 = Aquarium.create(fish_capacity: 5, price: 55)
a73 = Aquarium.create(fish_capacity: 8, price: 95)
a74 = Aquarium.create(fish_capacity: 15, price: 250)
a81 = Aquarium.create(fish_capacity: 3, price: 30)
a82 = Aquarium.create(fish_capacity: 5, price: 55)
a83 = Aquarium.create(fish_capacity: 8, price: 95)
a84 = Aquarium.create(fish_capacity: 15, price: 250)
a91 = Aquarium.create(fish_capacity: 3, price: 30)
a92 = Aquarium.create(fish_capacity: 5, price: 55)
a93 = Aquarium.create(fish_capacity: 8, price: 95)
a94 = Aquarium.create(fish_capacity: 15, price: 250)
a101 = Aquarium.create(fish_capacity: 3, price: 30)
a102 = Aquarium.create(fish_capacity: 5, price: 55)
a103 = Aquarium.create(fish_capacity: 8, price: 95)
a104 = Aquarium.create(fish_capacity: 15, price: 250)
a111 = Aquarium.create(fish_capacity: 3, price: 30)
a112 = Aquarium.create(fish_capacity: 5, price: 55)
a113 = Aquarium.create(fish_capacity: 8, price: 95)
a114 = Aquarium.create(fish_capacity: 15, price: 250)
a121 = Aquarium.create(fish_capacity: 3, price: 30)
a122 = Aquarium.create(fish_capacity: 5, price: 55)
a123 = Aquarium.create(fish_capacity: 8, price: 95)
a124 = Aquarium.create(fish_capacity: 15, price: 250)
a131 = Aquarium.create(fish_capacity: 3, price: 30)
a132 = Aquarium.create(fish_capacity: 5, price: 55)
a133 = Aquarium.create(fish_capacity: 8, price: 95)
a134 = Aquarium.create(fish_capacity: 15, price: 250)
a141 = Aquarium.create(fish_capacity: 3, price: 30)
a142 = Aquarium.create(fish_capacity: 5, price: 55)
a143 = Aquarium.create(fish_capacity: 8, price: 95)
a144 = Aquarium.create(fish_capacity: 15, price: 250)
a151 = Aquarium.create(fish_capacity: 3, price: 30)
a152 = Aquarium.create(fish_capacity: 5, price: 55)
a153 = Aquarium.create(fish_capacity: 8, price: 95)
a154 = Aquarium.create(fish_capacity: 15, price: 250)
a161 = Aquarium.create(fish_capacity: 3, price: 30)
a162 = Aquarium.create(fish_capacity: 5, price: 55)
a163 = Aquarium.create(fish_capacity: 8, price: 95)
a164 = Aquarium.create(fish_capacity: 15, price: 250)
a171 = Aquarium.create(fish_capacity: 3, price: 30)
a172 = Aquarium.create(fish_capacity: 5, price: 55)
a173 = Aquarium.create(fish_capacity: 8, price: 95)
a174 = Aquarium.create(fish_capacity: 15, price: 250)
a181 = Aquarium.create(fish_capacity: 3, price: 30)
a182 = Aquarium.create(fish_capacity: 5, price: 55)
a183 = Aquarium.create(fish_capacity: 8, price: 95)
a184 = Aquarium.create(fish_capacity: 15, price: 250)
a191 = Aquarium.create(fish_capacity: 3, price: 30)
a192 = Aquarium.create(fish_capacity: 5, price: 55)
a193 = Aquarium.create(fish_capacity: 8, price: 95)
a194 = Aquarium.create(fish_capacity: 15, price: 250)
a201 = Aquarium.create(fish_capacity: 3, price: 30)
a202 = Aquarium.create(fish_capacity: 5, price: 55)
a203 = Aquarium.create(fish_capacity: 8, price: 95)
a204 = Aquarium.create(fish_capacity: 15, price: 250)


u1 = User.create(user_name: 'foo', email: 'foo@example.com', password: 'qwerty', funds: 25000)




